---
title: "Homework 8"
author: "Fall 2016, Math 107, Prof. Adam Loy"
date: "Due Monday, November 14 at the beginning of class"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Problem 1
What percent of a standard normal distribution $\mathcal{N}(\mu=0,\ \sigma=1)$ is found in each region? Be sure to draw a graph as part of your answer, but you should use R to find the area. 

a. $Z < -1.35$
b. $Z > 1.48$
c. $-0.4 < Z < 1.5$
d. $|Z|>2$ (Hint: think about what values meet this specification and re-express this region without the absolute value.)

## Problem 2
A college senior who took the Graduate Record Examination exam scored 620 on the Verbal Reasoning section and 670 on the Quantitative Reasoning section. The mean score for Verbal Reasoning section was 462 with a standard deviation of 119, and the mean score for the Quantitative Reasoning was 584
with a standard deviation of 151. Suppose that both distributions are normal.

a. What is her Z-score on the Verbal Reasoning section? On the Quantitative Reasoning section? Draw a standard normal distribution curve and mark these two Z-scores on it.
b. What do these Z-scores tell you?
c. Relative to others, on which section did she do better?
d. Determine what percentile she was in for each section.
e. What percent of the test takers did better than her on the Verbal Reasoning section? On the Quantitative Reasoning section?
f. Now, let’s think more generally about the GRE. If a student scored in the 80th percentile on the Quantitative Reasoning section, what was their score?
g. If a student scored worse than 70% of the test takers in the Verbal Reasoning section, what was their score?


## Problem 3
The Capital Asset Pricing Model (CAPM) is a financial model that assumes returns on a portfolio are normally distributed. Suppose a portfolio has an average annual return of 14.7% (i.e. an average gain of 14.7%) with a standard deviation of 33%. A return of 0% means the value of the portfolio doesn't change, a negative return means that the portfolio loses money, and a positive return means that the portfolio gains money.

a. In what proportion of years does this portfolio lose money, i.e. have a return less than 0%?
b. What is the cutoff for the highest 15% of annual returns with this portfolio?
