---
title: "R code for “Intro to statistical graphics""
author: "Adam Loy"
date: "September 5, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## College majors that pay

Motivation: [The Economic Guide to Picking a College Major](http://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/)

```{r}
# Load the data

```

## Age of Congress

```{r}
# load packages
library(dplyr)
library(ggplot2)
library(ggthemes)

# Load the data
congress <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/congress-age/congress-terms.csv", na.strings = "", as.is = TRUE)

# Pull out 113 congress
c113 <- filter(congress, congress == 113)
c113$age <- as.numeric(c113$age)

# density plot
ggplot(data = c113, mapping = aes(x = age)) +
  geom_density() + 
  theme_minimal() +
  ggtitle("How old was the 113th Congress?")

```

## What do data scientists do all day?

```{r}
# Load the data
library(readxl)
library(viridis) # nicer color palettes
library(forcats) # categorical variables
library(ggthemes) # more plot themes
ds_survey <- read_excel("03-data/datasci-survey.xlsx")
ds_survey$time <- fct_inorder(ds_survey$time)

# facetted bar chart
ggplot(data = ds_survey, mapping = aes(x = time, y = percentage, fill = time)) + 
  geom_bar(stat = "identity") + 
  facet_wrap(~task) + 
  coord_flip() + 
  scale_fill_viridis(discrete=TRUE) + 
  labs(y = "% respondents", x = "") + 
  ggtitle("Where does a data scientists' time go?") +
  theme_minimal() + 
  theme(legend.position="none")
```

## Movie data set

```{r}
load(url("https://stat.duke.edu/~mc301/data/movies.Rdata"))

ggplot(data = movies, mapping = aes(x = critics_score, y = audience_score)) + 
  geom_point(alpha = 0.5) + 
  labs(x = "Critic score", y = "Audience score") +
  ggtitle("Does the audience agree with the critics?") +
  theme_minimal() +
  coord_fixed()

ggplot(data = movies, mapping = aes(x = critics_score, y = audience_score, color = best_pic_nom)) + 
  geom_point(alpha = 0.7) + 
  labs(x = "Critic score", y = "Audience score") +
  ggtitle("Does the audience agree with the critics?") +
  theme_minimal() +
  coord_fixed() + 
  scale_color_viridis(discrete = TRUE)

ggplot(data = movies, mapping = aes(x = critics_score, y = audience_score, color = best_pic_nom, shape = best_pic_nom)) + 
  geom_point(alpha = 0.7, data = filter(movies, best_pic_nom == "no")) + 
  geom_point(alpha = 0.7, data = filter(movies, best_pic_nom == "yes")) +
  labs(x = "Critic score", y = "Audience score") +
  ggtitle("Does the audience agree with the critics?") +
  theme_minimal() +
  coord_fixed()

ggplot(data = movies, mapping = aes(x = critics_score, y = audience_score)) + 
  geom_point(alpha = 0.5) + 
  labs(x = "Critic score", y = "Audience score") +
  ggtitle("Does the audience agree with the critics?") +
  theme_minimal() +
  coord_fixed() + 
  facet_wrap(~genre)

ggplot(data = movies, mapping = aes(x = critics_score, y = audience_score)) + 
  geom_point(alpha = 0.5) + 
  labs(x = "Critic score", y = "Audience score") +
  ggtitle("Does the audience agree with the critics?") +
  theme_minimal() +
  coord_fixed() + 
  facet_wrap(~mpaa_rating)

```

```{r}
# Movie histograms
library(ggplot2movies)
data("movies", package = "ggplot2movies")

ggplot(data = movies, mapping = aes(x = length)) + 
  geom_histogram(binwidth = 15, color = "gray20") +
  labs(x = "movie length (minutes)") +
  xlim(c(0,180))

ggplot(data = movies, mapping = aes(x = length)) + 
  geom_histogram(binwidth = 10, color = "gray20") +
  labs(x = "movie length (minutes)")

ggplot(data = movies, mapping = aes(x = length)) + 
  geom_histogram(binwidth = 5, color = "gray20") +
  labs(x = "movie length (minutes)")

ggplot(data = movies, mapping = aes(x = length)) + 
  geom_histogram(binwidth = 1, color = "gray20") +
  labs(x = "movie length (minutes)")


```


## Diamonds

```{r}
ggplot(data = diamonds, mapping = aes(x = carat)) + 
  geom_histogram(binwidth = 1, color = "gray20") + 
  theme_minimal() + 
  ggtitle("biwidth = 1")

ggplot(data = diamonds, mapping = aes(x = carat)) + 
  geom_histogram(binwidth = .1, color = "gray20") + 
  theme_minimal() + 
  ggtitle("biwidth = .1")

ggplot(data = diamonds, mapping = aes(x = carat)) + 
  geom_histogram(binwidth = .01, color = "gray20") + 
  theme_minimal() + 
  ggtitle("biwidth = .01")

```

```{r}
library(Lock5Data)
data("HollywoodMovies2011")
ggplot(data = filter(HollywoodMovies2011, Genre != "Adventure"), aes(x = reorder(Genre, Budget, median, na.rm = TRUE), y = Budget)) + 
  geom_boxplot() + coord_flip() + labs(x = "Genre", y = "Budget (millions)") + 
  ggtitle("Hollywood Budgets in 2011")
```

